import Vue from 'vue';

import MediaItem from '../../models/mediaItem';

export default Vue.extend({
    name: 'responsiveMediaItem',

    props: {
        breakpoints: Array,
        media: MediaItem,
    },

    data: function() {
        return {
            selectedBreakpoint: 0,
        };
    },

    computed: {
        activeBreakpoint(): number {
            if (this.selectedBreakpoint > 0) {
                return this.selectedBreakpoint as number;
            }

            return (this.media as MediaItem).getLargestBreakpoint();
        },

        activeName(): string {
            const source = (this.media as MediaItem).getSourceAt(this
                .activeBreakpoint as number);

            if (source === null) {
                const alternateSource = (this
                    .media as MediaItem).getSourceOrAlternative(this
                    .activeBreakpoint as number);

                return alternateSource
                    ? `Auto generated by ${alternateSource.breakpoint}`
                    : 'N/A';
            }

            return source.name;
        },

        orderedBreakpoints(): number[] {
            return (this.breakpoints as number[]).sort((a, b) => {
                return a - b;
            });
        },

        url(): string {
            return (this.media as MediaItem).getUrlAt(this
                .activeBreakpoint as number);
        },
    },

    methods: {
        update(): void {
            this.$emit('update', {
                media: (this as any).media,
                breakpoint: (this as any).activeBreakpoint,
            });
        },
    },

    template: `<div class="card">
        <img :src="url" class="card-img-top" alt="" />
        <div class="card-body flex-column">
            <p class="small">{{ activeName }}</p>

            <div class="d-flex flex-row flex-wrap mb-1">
                <button v-for="breakpoint in orderedBreakpoints" type="button" class="btn btn-secondary btn-sm mb-1 mr-1" v-on:click="selectedBreakpoint = breakpoint" v-bind:class="{ active: activeBreakpoint == breakpoint }">{{ breakpoint }}</button>
            </div>

            <div class="d-flex flex-row flex-wrap mb-2">
                <a href="#" class="mr-3" v-on:click.prevent="update">Change image at {{ activeBreakpoint }}</a>
            </div>
        </div>
    </div>`,
});
